version: '3.8'

services:
  growthness_api:
    container_name: growthness_api
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - growthness_redis
      - growthness_celery

  growthness_celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A growthness worker -l info  
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - growthness_redis

  growthness_redis:
    image: redis:6.2
    container_name: growthness_redis
    ports:
      - "6379:6379"

# Uncomment and modify this section if you want to use PostgreSQL as your database
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - .env
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

# volumes:
#   postgres_data:
